'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { FileText, ArrowLeft } from 'lucide-react';
import { Geist } from 'next/font/google';
import Link from 'next/link';
import { DottedSurface } from '@/components/ui/dotted-surface';
import { FloatingParticles } from '@/components/background-effects';
import { Navbar, TickerBar } from '@/components/navigation';

const geist = Geist({ subsets: ['latin'] });

export default function TermsPage() {
  return (
    <main className={`${geist.className} bg-[#0A0A0A] min-h-screen text-white relative overflow-hidden`}>
      <TickerBar />
      <Navbar />
      <DottedSurface />
      <FloatingParticles />
      
      <section className="relative z-10 pt-48 pb-24 px-8 max-w-4xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-[#444444] hover:text-white transition-colors mb-12">
          <ArrowLeft size={16} /> BACK TO HUB
        </Link>
        
        <div className="mb-16">
          <div className="inline-flex items-center gap-2 text-[#00FF94] text-[10px] font-bold mb-4 tracking-[0.2em] uppercase">
            <FileText size={12} /> PROTOCOL: TERMS_OF_SERVICE
          </div>
          <h1 className="text-5xl font-bold mb-6">Terms of Service</h1>
          <p className="text-[#888888] font-mono text-xs italic">LAST UPDATED: APRIL 18, 2026 // SYSTEM_VERSION: 1.0.4</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-12">
          <div className="p-8 border-2 border-[#1E1E1E] bg-[#111111] rounded-xl">
            <h2 className="text-xl font-bold text-white mb-4 uppercase tracking-wider">// 1.0 ACCEPTANCE OF TERMS</h2>
            <p className="text-[#888888] leading-relaxed">
              By accessing the PolyHedge Terminal and its associated data streams, you are entering into a binding legal agreement. 
              The signals provided are for institutional intelligence purposes and should not be construed as direct financial advice.
            </p>
          </div>

          <div className="p-8 border-2 border-[#1E1E1E] bg-[#111111] rounded-xl">
            <h2 className="text-xl font-bold text-white mb-4 uppercase tracking-wider">// 2.0 DATA CONDUCT</h2>
            <p className="text-[#888888] leading-relaxed">
              Redistribution of PolyHedge signals, MiroFish simulation data, or weightings to third-party entities is strictly prohibited 
              unless explicitly authorized via Enterprise API licensing.
            </p>
          </div>

          <div className="p-8 border-2 border-[#1E1E1E] bg-[#111111] rounded-xl">
            <h2 className="text-xl font-bold text-white mb-4 uppercase tracking-wider">// 3.0 RISK DISCLOSURE</h2>
            <p className="text-[#888888] leading-relaxed">
              Predictive modeling involves inherent variance. PolyHedge Data Systems is not liable for outcomes generated by 
              autonomous web agents or swarm intelligence vectors. All capital at risk belongs to the operator.
            </p>
          </div>
        </div>

        <footer className="mt-24 pt-12 border-t border-[#1E1E1E] text-center text-[#444444] text-xs">
          &copy; 2026 POLYHEDGE DATA SYSTEMS. ALL RIGHTS RESERVED.
        </footer>
      </section>
    </main>
  );
}
